version: "3"
services:
  worker:
    build: .
    networks:
      - app
    restart: always
    ports:
      - 3000:80
    volumes:
      - cache:/data
    environment:
      CONFIGOR_ENV_PREFIX: "APP"
      APP_SERVER_PORT: ":80"
      APP_SERVER_DATAFOLDER: "/data"
      APP_SERVER_PUBLIC: "http://localhost:3000"
      APP_DB_USER: root
      APP_DB_PASSWORD: 1
      APP_DB_HOST: appdb
      APP_DB_DATABASE: data
    links:
      - db:appdb

  db:
    networks:
      - app
    restart: always
    image: mysql:8.0
    volumes:
      - data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=1"
      - "MYSQL_DATABASE=data"

volumes:
  data:
  cache:

networks:
  app:
